language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
compiler:
 - gcc
 - clang
addons:
  apt:
    packages:
      - libjansson-dev
before_install:
 - git clean -x -f
 - ./autogen.sh
script:
 - ./configure
 - make -j4
 - make check -j4
 - pip install future
 - python pysearpc/test_pysearpc.py
notifications:
    email: false
